// 从 shared 包重新导出事件类型
export {
  NAMESPACE,
  ClientEvents,
  ServerEvents,
  type SubscribePayload,
  type UnsubscribePayload,
  type SessionInputPayload,
  type SessionResizePayload,
  type SessionStdoutPayload,
  type SessionPatchPayload,
  type SessionExitPayload,
  type SessionErrorPayload,
  type SessionIdPayload,
  type SessionSubscribedPayload,
  type SessionUnsubscribedPayload,
  type TaskUpdatedPayload,
  type TaskDeletedPayload,
  type TerminalInputPayload,
  type TerminalResizePayload,
  type TerminalStdoutPayload,
  type TerminalExitPayload,
  type TerminalSubscribedPayload,
  type TerminalUnsubscribedPayload,
  type AgentStatus,
  type AgentStatusPayload,
  type AckResponse,
  type ClientEventType,
  type ServerEventType,
} from '@agent-tower/shared/socket'
