/**
 * P0-2 property-based tests (contract §5.2).
 *
 * Three properties:
 *  1. the supported `(op, path)` set — canonical indices only, including
 *     out-of-range ones — always reaches the same verdict and the same document
 *     as `fast-json-patch`;
 *  2. the intentionally unsupported set (including non-canonical or
 *     non-representable `add` indices, §5.1) always degrades with a structured
 *     warning and is **not** compared to the baseline (it would succeed there);
 *  3. every successful in-range op shares all untouched entry references.
 */
import { afterEach, beforeEach, describe, expect, it, vi, type MockInstance } from 'vitest'
import fc from 'fast-check'
import { applyPatch, type AddOperation, type Operation, type ReplaceOperation } from 'fast-json-patch'
import type {
  ActionType,
  NormalizedEntry,
  NormalizedEntryType,
  ToolStatus,
} from '@agent-tower/shared/log-adapter'
import { applyConversationPatch, type NormalizedConversation } from '../conversation-patch'

let warnSpy: MockInstance

beforeEach(() => {
  warnSpy = vi.spyOn(console, 'warn').mockImplementation(() => {})
})

afterEach(() => {
  warnSpy.mockRestore()
})

// ---------------------------------------------------------------------------
// Generators
// ---------------------------------------------------------------------------

const actionArb = fc.constantFrom<ActionType>(
  'file_read',
  'file_edit',
  'command_run',
  'search',
  'tool',
  'other',
)
const statusArb = fc.constantFrom<ToolStatus>(
  'created',
  'pending',
  'in_progress',
  'success',
  'failed',
  'denied',
  'timed_out',
)
const entryTypeArb = fc.constantFrom<NormalizedEntryType>(
  'assistant_message',
  'tool_use',
  'user_message',
)

const idArb = fc.string({ minLength: 1, maxLength: 6 })
const contentArb = fc.string({ maxLength: 12 })

/** Metadata may be absent, and may or may not carry `status` (§5.2). */
const entryArb: fc.Arbitrary<NormalizedEntry> = fc.record(
  {
    id: idArb,
    timestamp: fc.integer({ min: 0, max: 2_000_000_000 }),
    entryType: entryTypeArb,
    content: contentArb,
    metadata: fc.record(
      {
        action: actionArb,
        toolName: fc.string({ maxLength: 4 }),
        status: statusArb,
        toolLocations: fc.array(
          fc.record({ path: fc.string({ maxLength: 8 }), line: fc.integer({ min: 0, max: 500 }) }),
          { maxLength: 2 },
        ),
      },
      { requiredKeys: ['action'] },
    ),
  },
  { requiredKeys: ['id', 'timestamp', 'entryType', 'content'] },
)

/** Same, but `metadata.status` always exists → every in-range op is applicable. */
const richEntryArb: fc.Arbitrary<NormalizedEntry> = fc.record({
  id: idArb,
  timestamp: fc.integer({ min: 0, max: 2_000_000_000 }),
  entryType: fc.constant<NormalizedEntryType>('tool_use'),
  content: contentArb,
  metadata: fc.record(
    {
      action: actionArb,
      toolName: fc.string({ maxLength: 4 }),
      status: statusArb,
    },
    { requiredKeys: ['action', 'status'] },
  ),
})

function conversation(entries: NormalizedEntry[]): NormalizedConversation {
  return { sessionId: 'session-1', entries, seq: entries.length }
}

function runBaseline(
  document: NormalizedConversation,
  patch: Operation[],
): { ok: true; document: NormalizedConversation } | { ok: false } {
  try {
    // `fast-json-patch` adopts `replace /entries` values by reference and later
    // ops mutate that array, so the baseline gets a private copy; otherwise it
    // would corrupt the patch the implementation under test is compared on.
    const result = applyPatch(document, structuredClone(patch), true, false)
    return { ok: true, document: result.newDocument as NormalizedConversation }
  } catch {
    return { ok: false }
  }
}

/** Index range that intentionally walks past both ends (contract §5.2). */
function boundaryIndexArb(length: number): fc.Arbitrary<number> {
  return fc.integer({ min: -1, max: length + 2 })
}

function inRangeIndexArb(length: number): fc.Arbitrary<number> {
  return fc.integer({ min: 0, max: Math.max(0, length - 1) })
}

/**
 * Index segment for `(op, path)` generation: canonical, sometimes padded with a
 * leading zero. Padded `add` indices are **not** baseline-equal any more — they
 * are an explicit divergence (§5.1) — so they are generated by
 * `divergentAddOpArb` below instead of the supported set. For `replace` they
 * stay in the supported set: the baseline rejects the raw `"00"` pointer too, so
 * both sides fail and the verdict still matches.
 */
function indexSegment(index: number, pad: boolean): string {
  return pad && index >= 0 ? `0${index}` : String(index)
}

/**
 * Index literals where `add` deliberately diverges from the baseline (§5.1):
 * non-canonical leading zeros, and values whose `~~key` (ToInt32) coercion wraps
 * them into a different, silently valid position — `4294967296`→0,
 * `9007199254740991`→-1, `9007199254740992`→0.
 */
const DIVERGENT_ADD_INDEX_SEGMENTS = [
  '00',
  '01',
  '007',
  '2147483648',
  '2147483649',
  '4294967296',
  '9007199254740991',
  '9007199254740992',
] as const

/** §1's six `(op, path)` pairs, with canonical boundary indices allowed. */
function supportedOpArb(length: number): fc.Arbitrary<Operation> {
  return fc.oneof(
    fc.tuple(fc.integer({ min: 0, max: length }), entryArb)
      .map(([index, value]) => ({
        op: 'add' as const,
        path: `/entries/${index}`,
        value,
      })),
    fc.tuple(boundaryIndexArb(length), entryArb)
      .map(([index, value]) => ({
        op: 'add' as const,
        path: `/entries/${index}`,
        value,
      })),
    fc.tuple(boundaryIndexArb(length), fc.boolean(), entryArb)
      .map(([index, pad, value]) => ({
        op: 'replace' as const,
        path: `/entries/${indexSegment(index, pad)}`,
        value,
      })),
    fc.tuple(boundaryIndexArb(length), fc.boolean(), contentArb)
      .map(([index, pad, value]) => ({
        op: 'replace' as const,
        path: `/entries/${indexSegment(index, pad)}/content`,
        value,
      })),
    fc.tuple(boundaryIndexArb(length), fc.boolean(), statusArb)
      .map(([index, pad, value]) => ({
        op: 'replace' as const,
        path: `/entries/${indexSegment(index, pad)}/metadata/status`,
        value,
      })),
    fc.string({ maxLength: 8 })
      .map((value) => ({ op: 'add' as const, path: '/sessionId', value })),
    fc.array(entryArb, { maxLength: 4 })
      .map((value) => ({ op: 'replace' as const, path: '/entries', value })),
  )
}

/** `add` index literals outside the canonical + exactly-representable rule. */
function divergentAddOpArb(): fc.Arbitrary<Operation> {
  return fc.tuple(fc.constantFrom(...DIVERGENT_ADD_INDEX_SEGMENTS), entryArb)
    .map(([segment, value]) => ({
      op: 'add' as const,
      path: `/entries/${segment}`,
      value,
    }))
}

/** Deliberately unsupported shapes (§5.1 intentional divergences + §4 unknown). */
function unsupportedOpArb(length: number): fc.Arbitrary<Operation> {
  return fc.oneof(
    divergentAddOpArb(),
    boundaryIndexArb(length)
      .map((index) => ({ op: 'remove' as const, path: `/entries/${index}` })),
    fc.tuple(boundaryIndexArb(length), boundaryIndexArb(length))
      .map(([from, to]) => ({
        op: 'move' as const,
        from: `/entries/${from}`,
        path: `/entries/${to}`,
      })),
    fc.tuple(boundaryIndexArb(length), boundaryIndexArb(length))
      .map(([from, to]) => ({
        op: 'copy' as const,
        from: `/entries/${from}`,
        path: `/entries/${to}`,
      })),
    fc.tuple(boundaryIndexArb(length), contentArb)
      .map(([index, value]) => ({ op: 'test' as const, path: `/entries/${index}/content`, value })),
    entryArb.map((value) => ({ op: 'add' as const, path: '/entries/-', value })),
    fc.constantFrom(
      '/nope',
      '/entries/0/metadata/other',
      '/entries/0/unknown',
      '/',
    ).map((path) => ({ op: 'replace' as const, path, value: 'x' })),
    // NOTE: `/entries` is *not* in this list. It is a supported path, and the
    // baseline assigns whatever value it is given (`doc.entries = value`), so a
    // wrong-typed value stays baseline-equal instead of degrading — see the
    // dedicated case in `conversation-patch.test.ts`.
    contentArb.map((value) => ({ op: 'add' as const, path: `/entries/${length}/content`, value })),
    fc.string({ maxLength: 4 })
      .map((value) => ({ op: 'replace' as const, path: '/sessionId', value })),
  )
}

function scenarioArb(
  opArb: (length: number) => fc.Arbitrary<Operation>,
): fc.Arbitrary<{ document: NormalizedConversation; patch: Operation[] }> {
  return fc.array(entryArb, { maxLength: 20 }).chain((entries) =>
    fc.record({
      document: fc.constant(conversation(entries)),
      patch: fc.array(opArb(entries.length), { minLength: 1, maxLength: 8 }),
    }),
  )
}

// ---------------------------------------------------------------------------
// Properties
// ---------------------------------------------------------------------------

// A failing property makes fast-check shrink the counterexample, and shrinking
// a `chain`ed scenario can explore a very large space; cap it so a regression
// surfaces as a failure instead of a hung test run.
const PROPERTY_OPTIONS = { numRuns: 400, interruptAfterTimeLimit: 30_000 } as const

describe('conversation patch property tests (§5.2)', () => {
  it('matches the baseline verdict and document for the supported op set', () => {
    fc.assert(
      fc.property(scenarioArb(supportedOpArb), ({ document, patch }) => {
        const before = JSON.stringify(document)
        const baseline = runBaseline(document, patch)
        const result = applyConversationPatch(document, patch)

        // Being more permissive than the baseline is forbidden, and for the
        // supported set there is no case where the baseline succeeds and this
        // implementation degrades.
        expect(result.ok).toBe(baseline.ok)
        if (baseline.ok && result.ok) {
          expect(JSON.stringify(result.conversation)).toBe(JSON.stringify(baseline.document))
        }
        // The input document is never mutated, even for failed batches.
        expect(JSON.stringify(document)).toBe(before)
      }),
      PROPERTY_OPTIONS,
    )
  })

  it('always degrades with a structured warning for the unsupported op set', () => {
    fc.assert(
      fc.property(scenarioArb(unsupportedOpArb), ({ document, patch }) => {
        warnSpy.mockClear()
        const before = JSON.stringify(document)
        const result = applyConversationPatch(document, patch)

        expect(result.ok).toBe(false)
        if (result.ok) return
        expect(result.kind).toBe('unsupported')
        expect(warnSpy).toHaveBeenCalled()
        expect(JSON.stringify(document)).toBe(before)
      }),
      { ...PROPERTY_OPTIONS, numRuns: 300 },
    )
  })

  it('always degrades for non-canonical or unrepresentable add indices (§5.1)', () => {
    fc.assert(
      fc.property(
        scenarioArb(() => divergentAddOpArb()),
        ({ document, patch }) => {
          warnSpy.mockClear()
          const before = JSON.stringify(document)
          const result = applyConversationPatch(document, patch)

          expect(result.ok).toBe(false)
          if (result.ok) return
          expect(result.kind).toBe('unsupported')
          expect(warnSpy).toHaveBeenCalled()
          expect(JSON.stringify(document)).toBe(before)
        },
      ),
      { ...PROPERTY_OPTIONS, numRuns: 200 },
    )
  })

  it('keeps every untouched entry reference stable for in-range single ops', () => {
    const identityArb = fc.array(richEntryArb, { minLength: 1, maxLength: 20 }).chain((entries) => {
      const length = entries.length
      const opArb: fc.Arbitrary<AddOperation<unknown> | ReplaceOperation<unknown>> = fc.oneof(
        fc.tuple(fc.integer({ min: 0, max: length }), richEntryArb)
          .map(([index, value]) => ({ op: 'add' as const, path: `/entries/${index}`, value })),
        fc.tuple(inRangeIndexArb(length), richEntryArb)
          .map(([index, value]) => ({ op: 'replace' as const, path: `/entries/${index}`, value })),
        fc.tuple(inRangeIndexArb(length), contentArb)
          .map(([index, value]) => ({
            op: 'replace' as const,
            path: `/entries/${index}/content`,
            value,
          })),
        fc.tuple(inRangeIndexArb(length), statusArb)
          .map(([index, value]) => ({
            op: 'replace' as const,
            path: `/entries/${index}/metadata/status`,
            value,
          })),
        fc.array(richEntryArb, { maxLength: 4 })
          .map((value) => ({ op: 'replace' as const, path: '/entries', value })),
      )
      return fc.record({ document: fc.constant(conversation(entries)), operation: opArb })
    })

    fc.assert(
      fc.property(identityArb, ({ document, operation }) => {
        const before = JSON.stringify(document)
        const result = applyConversationPatch(document, [operation])

        expect(result.ok).toBe(true)
        if (!result.ok) return
        const next = result.conversation
        const original = document.entries

        expect(next).not.toBe(document)
        if (operation.path === '/entries') {
          // Whole-array replacement: new array, shared elements.
          expect(next.entries).not.toBe(operation.value)
          expect(next.entries).toHaveLength((operation.value as NormalizedEntry[]).length)
          ;(operation.value as NormalizedEntry[]).forEach((item, index) => {
            expect(next.entries[index]).toBe(item)
          })
        } else {
          const segments = operation.path.split('/').slice(1)
          const index = Number(segments[1])
          expect(next.entries).not.toBe(original)

          if (operation.op === 'add') {
            for (let i = 0; i < index; i += 1) expect(next.entries[i]).toBe(original[i])
            for (let i = index + 1; i < next.entries.length; i += 1) {
              expect(next.entries[i]).toBe(original[i - 1])
            }
            expect(next.entries[index]).toBe(operation.value)
          } else {
            for (let i = 0; i < original.length; i += 1) {
              if (i !== index) expect(next.entries[i]).toBe(original[i])
            }
            expect(next.entries[index]).not.toBe(original[index])
            if (segments.length === 2) {
              expect(next.entries[index]).toBe(operation.value)
            } else if (segments[2] === 'content') {
              expect(next.entries[index].content).toBe(operation.value)
              expect(next.entries[index].metadata).toBe(original[index].metadata)
            } else {
              expect(next.entries[index].metadata).not.toBe(original[index].metadata)
              expect(next.entries[index].metadata?.status).toBe(operation.value)
            }
          }
        }

        // Untouched input must survive the apply byte for byte.
        expect(JSON.stringify(document)).toBe(before)
      }),
      { ...PROPERTY_OPTIONS, numRuns: 300 },
    )
  })
})
