export const ROOM_MESSAGE_COLLAPSED_LINE_COUNT = 10
export const ROOM_MESSAGE_COLLAPSED_LINE_HEIGHT = 24
export const ROOM_MESSAGE_COLLAPSED_MAX_HEIGHT =
  ROOM_MESSAGE_COLLAPSED_LINE_COUNT * ROOM_MESSAGE_COLLAPSED_LINE_HEIGHT

const ROOM_MESSAGE_OVERFLOW_TOLERANCE = 8

export function isRoomMessageContentOverflowing(
  scrollHeight: number,
  maxHeight = ROOM_MESSAGE_COLLAPSED_MAX_HEIGHT,
) {
  return scrollHeight > maxHeight + ROOM_MESSAGE_OVERFLOW_TOLERANCE
}
